### PR TITLE
Edited the footer.html and added the GitHub logo image 

### PR DESCRIPTION
**Pull request by nadia39**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@nadia39 Is this related to an issue? You can write #16 to reference an issue.

**Comment by niccokunzmann** [comment]
Where did you get the image from? This is important as we must be sure to do what is legal.

**Comment by niccokunzmann** [comment]
@nadia39 Can you check all is fine on the website?

**Comment by nadia39** [comment]
The image is from the website you showed me as an example/hint. Sorry for the late reply.

**Pull request merged**
