### PR TITLE
Add styling to blog post page

### PR DESCRIPTION
**Pull request by noncototient**
Hey,

Just added styling to the blog post page.

**Note: Links in footer to other posts are hardcoded for now. Probably need a plugin for it unless you just want to show links from predefined author URLs there.**

### CODE REVIEW

**Comment by Langleu** [comment]
thank you! :)

**Comment by noncototient** [comment]
My pleasure! Working on more

**Comment by niccokunzmann** [comment]
#19 Might be something you want to try.

**Comment by noncototient** [comment]
Will try

**Pull request merged**
