### PR TITLE
fix for footer icon etc

### PR DESCRIPTION
**Pull request by tekon92**
#30 
#33 trying to use provided svg  but the color of the svg and the background is the same so github logo not visible. and i create new css file since i dont wanna screw the current styling. please advice.

### CODE REVIEW

**Comment by tekon92** [comment]
@niccokunzmann hi mate. i done small changes.

**Comment by niccokunzmann** [comment]
@tekon92 Thanks!
I would have expected a pull-request for each change purpose (tutorial, issue) This way, I can decide the merge strategy: squash or merge.

**Comment by tekon92** [comment]
@niccokunzmann yeah I'm planning that way too. but on my recent pull request, my commit merged into one single pull request, even tho it should be 2 pull request. what did i missed?

**Comment by niccokunzmann** [comment]
Somewhere I wrote it but I can not find it now: with "git branch" you can create several branches. A pullr-equest refers to a branch.

**Pull request merged**
