### PR TITLE
Add footer navigation to post page

### PR DESCRIPTION
**Pull request by noncototient**
Not sure what is causing a merge conflict, and not sure what my steps should be at this point to resolve the conflict. Please let me know if I can/or you would like me to fix it myself.

### CODE REVIEW

**Comment by noncototient** [comment]
Ah, can see now what is causing it. Easy fix hopefully! :)

**Comment by niccokunzmann** [comment]
Okay

**Comment by niccokunzmann** [comment]
It is these two files. If you need help merging, you can tell me.

 _data/people.yml
dev/_posts/2017-03-22-serlo-zum-besuch-beim-schul-loud-team.md 

I change the author in the mean time.

**Comment by noncototient** [comment]
@niccokunzmann attempted to fix the merge conflict, please take a look!

**Comment by niccokunzmann** [comment]
Thanks! If you like, you can look over the page and create issues where you see something is not as perfect as you want it to be.

**Comment by noncototient** [comment]
@niccokunzmann sure thing! Will do! Was wondering about the navigation in here #14, could you please clarify what exactly you're looking for?

**Pull request merged**
