### PR TITLE
Header add to the blog post

### PR DESCRIPTION
**Pull request by bksahu**
All done as per said. I am looking forward for your suggestions.

### CODE REVIEW

**Comment by bksahu** [comment]
@niccokunzmann I have no idea why all checks have failed. Could you please help me with that ?

**Comment by niccokunzmann** [comment]
That is fine. I am experimenting with them and put these experiments into another branch.

**Comment by niccokunzmann** [comment]
Thanks again!

**Comment by bksahu** [comment]
Thanks for being so helpful :smile:

**Pull request merged**
